/**
 * Configuration des célébrations pour chaque milestone
 */

import { CelebrationConfig, MilestoneType } from '../types/celebration.types';

export const CELEBRATION_CONFIGS: Record<MilestoneType, CelebrationConfig> = {
  yams: {
    type: 'yams',
    title: 'YAMS !!!',
    subtitle: '50 points',
    emoji: '👑',
    duration: 3000,
    confetti: true,
    confettiColors: ['#FFD700', '#FFA500', '#FF6B6B', '#4A90E2'],
    confettiCount: 150,
    sound: 'yams_fanfare',
    haptic: 'heavy',
    fullScreen: true,
    priority: 10,
  },

  largeStraight: {
    type: 'largeStraight',
    title: 'GRANDE SUITE !',
    subtitle: '40 points',
    emoji: '🚀',
    duration: 2500,
    confetti: true,
    confettiColors: ['#4A90E2', '#5DADE2', '#FFFFFF'],
    confettiCount: 100,
    sound: 'rocket_launch',
    haptic: 'heavy',
    fullScreen: true,
    priority: 8,
  },

  fullHouse: {
    type: 'fullHouse',
    title: 'FULL HOUSE !',
    subtitle: '25 points',
    emoji: '🏠',
    duration: 2000,
    confetti: true,
    confettiColors: ['#50C878', '#3FA065', '#FFD700'],
    confettiCount: 80,
    sound: 'house_build',
    haptic: 'medium',
    fullScreen: false,
    priority: 6,
  },

  bonus: {
    type: 'bonus',
    title: 'BONUS DÉBLOQUÉ !',
    subtitle: '+35 points',
    emoji: '⭐',
    duration: 2500,
    confetti: true,
    confettiColors: ['#FFD700', '#FFA500', '#FFEB3B'],
    confettiCount: 120,
    sound: 'bonus_unlock',
    haptic: 'heavy',
    fullScreen: true,
    priority: 9,
  },

  perfectScore: {
    type: 'perfectScore',
    title: 'SCORE PARFAIT !',
    subtitle: 'Maximum atteint',
    emoji: '💎',
    duration: 2000,
    confetti: true,
    confettiColors: ['#4A90E2', '#50C878', '#FFD700'],
    confettiCount: 100,
    sound: 'perfect',
    haptic: 'success',
    fullScreen: false,
    priority: 7,
  },

  comeback: {
    type: 'comeback',
    title: 'COMEBACK INCROYABLE !',
    subtitle: 'De dernier à premier',
    emoji: '🔥',
    duration: 2500,
    confetti: true,
    confettiColors: ['#FF6B6B', '#FFA500', '#FFD700'],
    confettiCount: 150,
    sound: 'comeback',
    haptic: 'heavy',
    fullScreen: true,
    priority: 9,
  },

  leadChange: {
    type: 'leadChange',
    title: 'Nouveau Leader !',
    emoji: '👑',
    duration: 1500,
    confetti: true,
    confettiColors: ['#FFD700', '#FFA500'],
    confettiCount: 60,
    sound: 'lead_change',
    haptic: 'medium',
    fullScreen: false,
    priority: 5,
  },

  firstBlood: {
    type: 'firstBlood',
    title: 'Première marque !',
    emoji: '🎯',
    duration: 1000,
    confetti: false,
    sound: 'first_score',
    haptic: 'light',
    fullScreen: false,
    priority: 2,
  },

  closeGame: {
    type: 'closeGame',
    title: 'Partie serrée !',
    emoji: '🔥',
    duration: 1500,
    confetti: false,
    sound: 'tension',
    haptic: 'medium',
    fullScreen: false,
    priority: 3,
  },

  perfectGame: {
    type: 'perfectGame',
    title: 'PARTIE PARFAITE !',
    subtitle: 'Aucun zéro',
    emoji: '💎',
    duration: 3000,
    confetti: true,
    confettiColors: ['#4A90E2', '#50C878', '#FFD700', '#FF6B6B'],
    confettiCount: 200,
    sound: 'perfect_game',
    haptic: 'heavy',
    fullScreen: true,
    priority: 10,
  },

  shutout: {
    type: 'shutout',
    title: 'DOMINATION !',
    subtitle: '+100 points d\'écart',
    emoji: '💪',
    duration: 2000,
    confetti: true,
    confettiColors: ['#FFD700', '#FFA500'],
    confettiCount: 100,
    sound: 'domination',
    haptic: 'heavy',
    fullScreen: false,
    priority: 7,
  },

  highScore: {
    type: 'highScore',
    title: 'SCORE LÉGENDAIRE !',
    subtitle: 'Plus de 250 points',
    emoji: '🏆',
    duration: 2500,
    confetti: true,
    confettiColors: ['#FFD700', '#FFA500', '#FF6B6B'],
    confettiCount: 150,
    sound: 'legendary',
    haptic: 'heavy',
    fullScreen: true,
    priority: 9,
  },
};

// Sounds paths (à créer ou utiliser des sons système)
export const SOUND_FILES: Record<string, string> = {
  yams_fanfare: 'yams_fanfare.mp3',
  rocket_launch: 'rocket_launch.mp3',
  house_build: 'house_build.mp3',
  bonus_unlock: 'bonus_unlock.mp3',
  perfect: 'perfect.mp3',
  comeback: 'comeback.mp3',
  lead_change: 'lead_change.mp3',
  first_score: 'first_score.mp3',
  tension: 'tension.mp3',
  perfect_game: 'perfect_game.mp3',
  domination: 'domination.mp3',
  legendary: 'legendary.mp3',
  tap: 'tap.mp3',
  score_entry: 'score_entry.mp3',
};
